### Site Settings ###
title               : Erick Castillo
description         : >-
                      Half biologist, half coder, fully confused (but making progress) 
baseurl             : ""           
repository          : ErickCastilloVargas/ErickCastilloVargas.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Erick Castillo
  image             : img/me.png
  email             : erickmarcoscastillovargas@gmail.com
  github            : ErickCastilloVargas
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : erick-marcos-castillo-vargas-68318a221
  orcid             : 0009-0009-7152-9116
# stackoverflow     : your_user_id
# twitter           : your_username
# youtube           : your_channel_name


### Events ###
permalink: /events/:title


### Collections ###
collections:
  publications:
    output: true
    permalink: /publications/:name
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                    


### Analytics ###
analytics:
  enabled: false                                        
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
